name: Invalidate CloudFront Cache

# Required repository secrets:
#   AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY - programmatic user or role creds
#   AWS_REGION - region where your CloudFront distribution is managed
#   CLOUDFRONT_DISTRIBUTION_IDS - space- or newline-separated IDs (e.g. "E123ABC456789 E182DMQC2ZDWSY")

on:
  push:
    branches:
      - master

jobs:
  invalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront cache(s)
        env:
          DISTRIBUTION_IDS: ${{ secrets.CLOUDFRONT_DISTRIBUTION_IDS }}
        run: |
          if [ -z "${DISTRIBUTION_IDS}" ]; then
            echo "CLOUDFRONT_DISTRIBUTION_IDS secret is not set" >&2
            exit 1
          fi

          for id in $DISTRIBUTION_IDS; do
            echo "Invalidating CloudFront distribution $id"
            aws cloudfront create-invalidation --distribution-id "$id" --paths '/*'
          done
